apiVersion: v1
kind: Secret
metadata:
  name: acr-login
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${BASE64_DOCKER_CONFIG_JSON}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-url
type: Opaque
data:
  spring_data_mongodb_uri: ${MONGODB_URI_64}